### ISSUE TITLE
Improve documentation (was: NuLib is old, try NuLib2)

### ISSUE THREAD

**Issue by nerun** [johnsonjh/nulib#11]
Hey,

Last version of `NuLib` was `3.2.5`:
https://nulib.com/downloads/

Also, there is a new version called `NuLib2` (v3.1.0 now) that superseded this one, developed by the same author [Andy McFadden](https://github.com/fadden):
https://github.com/fadden/nulib2

Read my issue in NuLib2 page: https://github.com/fadden/nulib2/issues/12

Cheers!

**Comment by johnsonjh** [comment]
@nerun 

Oh, thanks for the pointer, I didn't know that NuLib 3.2.5 was released. It seems to do essentially the same thing as this version does - that is, make it possible to build the same "old" code on a modern system.

I will have a look at the changes and merge those into the repository here, if applicable, unless @fadden has objections.

I will also update this repository to point to NuLib2 (and the authors current repository).  

I will also clarify the (mostly historical) purposes of this repository in the README.

There are a few reasons I made this repository, such as,

* NuLib2 (at least out of the box), doesn't attempt to support building on MS-DOS, GS/OS, or other 16-bit platforms that were contemporary with the IIe (and these archives).

* I have this version of NuLib working on CP/M-68K and Xenix.

* While it may be possible to build NuLib2 for these older systems, those changes would (probably) not be able to be easily tested and maintained in future NuLib2 releases.  

So, rather than backport NuLib2, I decided to do some minor clean-up of NuLib. While this was mostly for my own use, I made this repository as a public "backup" and to share it, in case it might be useful to others.

NuLib2 should be preferred version in almost all cases.

**Comment by nerun** [comment]
Thank you! If you don't mind, closing the issue.

**Comment by johnsonjh** [comment]
Also, I should make it clearer that any issues with this version of NuLib should be attributed to me, and not @fadden.

I'm going to keep this issue for now, mostly as a reminder to myself, and close when I update the documentation in the coming days.

**Comment by fadden** [comment]
NuLib v3.2.5 (or v3.25... version numbers are hard) fixed a bunch of minor bugs, but IIRC most of what Devin Reade was trying to do was improve compatibility with various systems and compilers, including specifically Orca/C and GNO on the Apple IIgs.  AFAIK it should work at least as well as v3.2.4 on the older systems, but it's been a very long time since I've tried.

**Comment by johnsonjh** [comment]
Bumping so I don't forget to compare and merge any changes and document the purpose and differences.
